function export_to_csv(data, cfg)
%EXPORT_TO_CSV  Save simulated dataset as CSV file

N = cfg.N_total;

% Build table
T = table(...
    data.wafer_id, ...
    data.product, ...
    data.site_number, ...
    data.touchdowns, ...
    round(data.cres, 4), ...
    round(data.zHeight, 2), ...
    round(data.over_travel, 2), ...
    round(data.planarity, 2), ...
    round(data.tip_diam, 2), ...
    round(data.fc, 3), ...
    round(data.temperature, 1), ...
    data.bin_number, ...
    data.needle_status, ...
    data.defect_pattern, ...
    'VariableNames', { ...
        'Wafer_ID', 'Product', 'Site_Number', 'Touchdowns', ...
        'CRES_Ohm', 'zHeight_um', 'OverTravel_um', 'Planarity_um', ...
        'TipDiameter_um', 'AppliedForce_Fc_g', 'Temperature_C', ...
        'Bin_Number', 'Needle_Status', 'Defect_Pattern'});

out_path = fullfile(cfg.output_dir, 'wafer_probing_dataset.csv');
writetable(T, out_path);
end


function print_results_table(results)
%PRINT_RESULTS_TABLE  Print formatted summary table to console

fprintf('\n%-18s %10s %10s %10s %10s\n', 'Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score');
fprintf('%s\n', repmat('-', 1, 62));
models = {'SVM', 'DecisionTree', 'RandomForest'};
for m = 1:3
    r = results.(models{m});
    fprintf('%-18s %9.2f%% %9.2f%% %9.2f%% %9.2f%%\n', ...
        models{m}, r.accuracy, r.precision, r.recall, r.f1);
end
fprintf('%s\n', repmat('-', 1, 62));
fprintf('Paper target: Accuracy > 95%%\n\n');
fprintf('Output files saved to outputs/ folder:\n');
fprintf('  - wafer_probing_dataset.csv\n');
fprintf('  - Fig1_CRES_vs_Touchdowns.png\n');
fprintf('  - Fig2_Yield_vs_Touchdowns.png\n');
fprintf('  - Fig3_Feature_Distributions.png\n');
fprintf('  - Fig4_Defect_Product_Summary.png\n');
fprintf('  - Fig5_Confusion_Matrices.png\n');
fprintf('  - Fig6_Model_Comparison.png\n');
end
